export const LOAD_ARTICLES_REQUEST = "LOAD_ARTICLES_REQUEST";
export const LOAD_ARTICLES_FAILURE = "LOAD_ARTICLES_FAILURE";
export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";

export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
